#	Workstream	Task	Owner	Responsibility	Dependency	Status	Priority	Timeline	Notes
1.1	WS1 – Phase 1 Completion & Prerequisites	Confirm Phase 1 AWS Data Lake is stable and all ETL pipelines operational	DMINE Eng	Accountable	Phase 1 sign-off	In Progress	High	Pre Phase 2	99% data quality SLA must be met for 3 consecutive months
1.2	WS1 – Phase 1 Completion & Prerequisites	Data quality SLA validation across all domains (Fraud / AML / Customer / Reference)	DMINE Eng / Data Gov	Accountable / Consulted	1.1	Not Started	High	Pre Phase 2	Business domain owners must sign off before analytics layer is built
1.3	WS1 – Phase 1 Completion & Prerequisites	Decommission unused Sybase IQ / DMINE jobs (no consumption in last 90–180 days)	DMINE Eng / Business	Accountable / Approver	1.1	Not Started	Medium	Pre Phase 2	Data cleanup — requires business sign-off before decommissioning any job
1.4	WS1 – Phase 1 Completion & Prerequisites	Finalise Phase 2 scope / budget approval and executive sign-off	Business / Data Gov	Approver	1.1, 1.2	Not Started	Critical	Pre Phase 2	Scope: Sec2, MSBI, BI/Analytics, model deployment, report migration
1.5	WS1 – Phase 1 Completion & Prerequisites	Cloud platform selection for Phase 2 — AWS vs Azure decision	Cloud Arch / Business	Accountable / Approver	1.4	Not Started	Critical	Pre Phase 2	Evaluate AWS (SageMaker, QuickSight, Redshift) vs Azure (Synapse, Power BI, Azure ML)
2.1	WS2 – Sec2 Modernization	Inventory all Sec1/Sec2 SQL Server objects (tables / views / stored procs / linked servers)	DMINE Eng / BI Team	Responsible	1.4	Not Started	High	Phase 2 – Month 1–2	Full audit — identify actively consumed vs can be retired
2.2	WS2 – Sec2 Modernization	Map all Sec2 data flows to new AWS/Azure platform equivalents	Cloud Arch / DMINE Eng	Responsible	2.1	Not Started	High	Phase 2 – Month 2–3	Currently Sec2 fetches from AWS Data Lake; Phase 2 eliminates Sec2 entirely
2.3	WS2 – Sec2 Modernization	Migrate Sec2 SSAS cubes to cloud-native analytics engine	Cloud Arch / BI Team	Responsible	1.5, 2.2	Not Started	High	Phase 2 – Month 3–5	SSAS cubes feed Excel and SSRS reports — replace with cloud semantic layer
2.4	WS2 – Sec2 Modernization	Migrate SSRS reports from Sec1/Sec2 to new BI platform (Power BI)	BI Team	Responsible	2.3	Not Started	High	Phase 2 – Month 4–6	Catalogue all SSRS reports / identify active ones / migrate to Power BI
2.5	WS2 – Sec2 Modernization	Decommission Sec1/Sec2 SQL Servers post-migration validation	DMINE Eng / Business	Accountable / Approver	2.4, 3.4	Not Started	Medium	Phase 2 – Month 7–8	Parallel run required; decommission only after 100% report migration confirmed
3.1	WS3 – MSBI Component Migration	Inventory all SSIS packages and ETL jobs running in MSBI stack	DMINE Eng	Responsible	1.4	Not Started	High	Phase 2 – Month 1–2	Classify components: migrate, retire, or rebuild
3.2	WS3 – MSBI Component Migration	Re-engineer SSIS pipelines to AWS Glue / Azure Data Factory equivalents	DMINE Eng / Cloud Arch	Responsible	1.5, 3.1	Not Started	High	Phase 2 – Month 2–5	Identify gaps not covered by Phase 1 Glue ETL and build new pipelines
3.3	WS3 – MSBI Component Migration	Migrate BMA (Business Model Analytics) data pipelines to cloud platform	DMINE Eng	Responsible	3.2	Not Started	High	Phase 2 – Month 3–5	BMA data used by Fraud Analytics and AML — high priority for model scoring
3.4	WS3 – MSBI Component Migration	Validate all migrated MSBI components with business stakeholders (UAT)	BI Team / Business	Responsible / Approver	3.2, 3.3	Not Started	High	Phase 2 – Month 5–6	Data must reconcile with legacy outputs — formal UAT sign-off required
4.1	WS4 – BI & Analytics Layer	Define target analytics architecture (Redshift / Synapse / Databricks)	Cloud Arch / Data Gov	Accountable	1.5	Not Started	Critical	Phase 2 – Month 1	Must support Power BI, SAS Viya, DataIKU, Jupyter — tools used across FCU teams
4.2	WS4 – BI & Analytics Layer	Build curated / Gold layer in data lake for analytics consumption	DMINE Eng	Responsible	1.2, 4.1	Not Started	Critical	Phase 2 – Month 2–4	Analytics-ready datasets — aggregated, business-rule applied, domain-organised
4.3	WS4 – BI & Analytics Layer	Migrate existing Power BI reports and dashboards to new platform	BI Team	Responsible	4.1, 4.2	Not Started	High	Phase 2 – Month 4–6	6 FCU teams use Power BI — all dashboards to be migrated with new data connections
4.4	WS4 – BI & Analytics Layer	Enable self-service analytics workspace for FCU users (ad hoc queries)	Cloud Arch / BI Team	Responsible	4.2	Not Started	High	Phase 2 – Month 5–7	Requested by Fraud Analytics — workspace to consume from Data Lake and other sources
4.5	WS4 – BI & Analytics Layer	Integrate SAS Viya and DataIKU with new cloud data platform	Cloud Arch / DMINE Eng	Responsible	4.1, 4.2	Not Started	High	Phase 2 – Month 4–6	SAS Viya (5 teams) and DataIKU (5 teams) heavily used — maintain connectivity
4.6	WS4 – BI & Analytics Layer	WebLog data integration for future Power BI reporting	DMINE Eng	Responsible	4.2	Not Started	Low	Phase 2 – Month 7+	Future use case identified by Fraud BI & Reporting team
5.1	WS5 – Model Deployment & ML	Define ML/Model deployment platform (SageMaker / Azure ML / Databricks MLflow)	Cloud Arch / Business	Accountable / Approver	1.5	Not Started	Critical	Phase 2 – Month 1–2	Data Gov manages 40+ fraud/AML models — platform must support monitoring and versioning
5.2	WS5 – Model Deployment & ML	Migrate existing fraud/AML predictive models to cloud ML platform	DMINE Eng / Data Gov	Responsible	4.2, 5.1	Not Started	High	Phase 2 – Month 4–7	40+ models in production — phased migration with parallel run and validation
5.3	WS5 – Model Deployment & ML	Implement model monitoring and ongoing validation framework	Data Gov	Responsible	5.2	Not Started	High	Phase 2 – Month 6–8	Currently done via Informatica + Ataccama — replicate on cloud platform
5.4	WS5 – Model Deployment & ML	Enable Jupyter Notebook environment for data science teams	Cloud Arch	Responsible	5.1, 4.2	Not Started	Medium	Phase 2 – Month 5–6	Identified as future tool by Fraud Analytics and ADA teams
6.1	WS6 – Data Governance & Compliance	Extend data catalogue (Collibra / Alation) to cover Phase 2 analytics assets	Data Gov	Responsible	4.1	Not Started	High	Phase 2 – Month 2–4	Business glossary, lineage, and field definitions for all new analytics datasets
6.2	WS6 – Data Governance & Compliance	Implement RBAC for analytics platform — integrate with SailPoint	Cloud Arch / Data Gov	Responsible	4.1	Not Started	High	Phase 2 – Month 2–4	Unmasked/PII data access required by multiple FCU teams — SailPoint governance
6.3	WS6 – Data Governance & Compliance	PIPEDA / OSFI / FINTRAC compliance validation for Phase 2 analytics layer	Data Gov / Business	Responsible / Approver	4.2, 6.2	Not Started	Critical	Phase 2 – Month 5–7	All PII/sensitive data flows reviewed by compliance before Phase 2 go-live
6.4	WS6 – Data Governance & Compliance	Extend ServiceNow access request workflow to Phase 2 analytics users	Data Gov	Responsible	6.2	Not Started	Medium	Phase 2 – Month 4–5	Existing ServiceNow workflow from Phase 1 extended to new analytics datasets and tools
7.1	WS7 – Enablement / Training & Cutover	Train FCU users on new analytics platform and self-service tools	BI Team / Data Gov	Responsible	4.3, 4.4	Not Started	High	Phase 2 – Month 6–8	44+ users across 8 teams — training per tool (Power BI, SAS Viya, DataIKU, Jupyter)
7.2	WS7 – Enablement / Training & Cutover	Parallel run period — validate new platform outputs vs Sec2 legacy	DMINE Eng / BI Team	Responsible	4.3, 2.4	Not Started	Critical	Phase 2 – Month 7–8	Minimum 4–6 weeks parallel run; business teams validate before cutover
7.3	WS7 – Enablement / Training & Cutover	Business sign-off and formal Phase 2 cutover approval	Business / Data Gov	Approver	7.2, 5.2, 2.5	Not Started	Critical	Phase 2 – Month 8–9	VP Fraud Risk, VP AML Compliance, CDO sign-off required before decommission
7.4	WS7 – Enablement / Training & Cutover	Decommission legacy DMINE / Sybase IQ and Sec2 infrastructure	DMINE Eng / Cloud Arch	Responsible	7.3	Not Started	High	Phase 2 – Month 9+	Archive data per 7-year regulatory retention policy before decommission